###
GET http://127.0.0.1:3000/ HTTP/1.1

###
GET http://127.0.0.1:3000/users?username=William HTTP/1.1

###
GET http://127.0.0.1:3000/users/William HTTP/1.1

###
POST http://127.0.0.1:3000/users HTTP/1.1
Content-Type: application/json

{
    "username": "William",
    "password": "040720william"
}

###
GET http://127.0.0.1:3000/src/main HTTP/1.1

###
GET http://127.0.0.1:3000/Cargo.toml HTTP/1.1
